const config = new Map();
config.set('svhost','localhost');
config.set('svport','8000');
config.set('dbhost','localhost');
config.set('dbport',3306);
config.set('dbcharset','utf8mb4');
config.set('dbuser','root');
config.set('dbpassword','jsb');
config.set('database','userbehave');
module.exports = config;
